name: flutter_app_welcome
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/flutterCircle.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "images/flutterCircle.png"
    # background_color: "#hexcode"
    # theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/flutterCircle.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "images/flutterCircle.png"

flutter:
  uses-material-design: true

  assets:
    - images/
 
